### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by blueoceanyyc** [NCRCounterpointAPI/APIGuide#142]
Hello Mike - Can you reopen this issue? We have a client using the API and they rebooted their sever last night and now all our API requests are getting this exact exception/error message. 

(
    [ResponseStatus] => stdClass Object
        (
            [ErrorCode] => ArgumentException
            [Message] => An item with the same key has already been added.
            [StackTrace] =>    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at CPAPI.Common.RegistrationIniBusiness.ValidateRegistrationFile(String dbName)
   at CPAPI.Common.RegIniAttribute.Execute(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.RequestFilterAttribute.RequestFilter(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.Host.RestHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)
        )

)

The API has been working for the past year and no changes were made to the api registration files. We double checked and the api license files do not expire until Aug 30, 2019. In our setup, we have our main company and our test/practice company but the names are different. Please advise. Thanks!

_Originally posted by @blueoceanyyc in https://github.com/NCRCounterpointAPI/APIGuide/issues/47#issuecomment-462972972_

**Comment by PhilipLooney** [comment]
My name is Philip Looney, and I am the Product Manager for NCR Counterpoint.

The NCR Counterpoint API is still be supported and enhanced, however this Github forum is NOT being actively monitored by our NCR Support team, and should not be used to report issues with the API. 

To report issues with the Counterpoint API, please email our support team at Support.sql@ncr.com or you may call 800.533.2277.  They will capture the issue for our API Development team to resolve/respond to.

I have captured your issue above and passed it on to our support team.

**Comment by blueoceanyyc** [comment]
Thanks for the reply. We actually just resolved the issue yesterday. Our registration.ini file was overwritten and needed to be regenerated. Once that was done it was fixed

Cheers,
James Keichinger, B.Sc.
Principal

[signature_1634593929]

Office: 403.455.1658
1732 11th Avenue SW, Calgary, AB -  www.blueoceaninteractive.com<http://www.blueoceaninteractive.com/>

CONFIDENTIALITY NOTICE
The information contained in this transmittal is personal and confidential. It is intended solely for the use of the individual or entity named. Please be advised that any reading, copying, disclosure, approbation, or dissemination of the contents of this email by anyone other than the named recipient is strictly prohibited. If you have received this communication in error, please notify us immediately.

**Comment by Bflatt** [comment]
James,  

Good afternoon.    I, for the first time on a site, am seeing this message as well.    The registration. ini file is newly installed.   Are you saying NCR needs to regenerate a NEW registration key.   The current files does have the api included.  

Any assistance is appreciated.  


Many thanks 

Bill
