### ISSUE TITLE
Getting Error Invalid Registration when we hit https://php70:52000/Customers using postman

### ISSUE THREAD

**Issue by amitcorcrm** [NCRCounterpointAPI/APIGuide#20]
I have facing an error an Exception when we try to access company endpoint API using Postman. I have also created a role from CounterPoint API console and assign it to the user as well.
![screenshot_3](https://cloud.githubusercontent.com/assets/26566972/25742883/43d5a7d4-31af-11e7-826e-f2fa76b11868.png)
 
I am attaching the Error log s well as..--------------------

2017-05-05T14:13:06.09096 INFO 1 ServiceStackHost Initializing Application NCR Counterpoint Rest API took 5343.8024ms. No errors detected.
2017-05-05T14:13:06.09296 DEBUG 4 WinService Service Starting
2017-05-05T14:13:06.10747 DEBUG 4 WinService Service Started
2017-05-05T14:13:28.21173 DEBUG 8 AppSelfHostBase 192.168.0.61:52000 Request : /app/index.htm
2017-05-05T14:13:28.45778 DEBUG 8 AppSelfHostBase 192.168.0.61:52000 Request : /styles/bootstrap/bootstrap.css
2017-05-05T14:13:28.69583 DEBUG 7 AppSelfHostBase 192.168.0.61:52000 Request : /app/views/unauthorized.htm
2017-05-05T14:13:28.69783 DEBUG 8 AppSelfHostBase 192.168.0.61:52000 Request : /app/views/editRoles.htm
2017-05-05T14:13:30.02506 DEBUG 8 AppSelfHostBase 192.168.0.61:52000 Request : /app/views/login.htm
2017-05-05T14:13:37.29131 DEBUG 8 AppSelfHostBase 192.168.0.61:52000 Request : /auth
2017-05-05T14:13:37.56136 DEBUG STP SmartThreadPool Thread #2 OrmLiteReadCommandExtensions SQL: SELECT "USR_ID", "NAM", "NAM_UPR", "INITIALS", "PWD", "ADRS_1", "ADRS_2", "ADRS_3", "CITY", "STATE", "ZIP_COD", "CNTRY", "CONTCT_1", "CONTCT_2", "PHONE_1", "PHONE_2", "FAX_1", "FAX_2", "EMAIL_ADRS_1", "EMAIL_ADRS_2", "URL_1", "URL_2", "WRKGRP_ID", "ALLOW_OTHR_WRKGRPS", "DEPT", "EMP_NO", "SEC_COD", "IS_PS_USR", "IS_PS_MGR", "PS_SEC_COD", "IS_SLS_REP", "IS_BUYER", "LOGIN_DISABLED", "CHNG_PWD_NXT_LOGIN", "LST_PWD_CHNG_DAT", "LST_LOGIN_DT", "LST_STR_ID", "LST_STA_ID", "LST_DRW_ID", "COMMIS_COD", "LST_MAINT_DT", "LST_MAINT_USR_ID", "LST_LCK_DT", "LST_WRKGRP_ID", "LOGIN_FAIL_CNT", "PREV_PWD_1", "PREV_PWD_2", "PREV_PWD_3", "LST_CLCK_IN_DT", "LST_CLCK_OUT_DT", "BIO_ID_DATA", "LST_LOGIN_WKSTN_NAM", "LST_TE_LOGIN_DT", "LST_TE_WRKGRP_ID", "LST_TE_LOGIN_WKSTN_NAM", "COPY_FRM_USR_ID", "RS_UTC_DT", "IS_MAIL_MGR", "ALLOW_SEND_POPUPMAIL", "IS_OM_USR", "RS_STAT", "RPT_EMAIL", "MSR_LOGIN_ID_1", "MSR_LOGIN_ID_2" FROM "SY_USR" WHERE "USR_ID" = @USR_ID
PARAMS: USR_ID=MGR
2017-05-05T14:13:37.78340 DEBUG STP SmartThreadPool Thread #2 OrmLiteReadCommandExtensions SQL: SELECT "KEY_ID", "NAM", "ADRS_1", "ADRS_2", "ADRS_3", "CITY", "STATE", "ZIP_COD", "CNTRY", "PHONE_1", "PHONE_2", "CONTCT_1", "CONTCT_2", "FAX_1", "FAX_2", "EMAIL_ADRS_1", "EMAIL_ADRS_2", "URL_1", "URL_2", "CURR_CALNDR_ID", "CENTURY_OFFSET", "USE_PWDS", "MIN_PWD_LEN", "PWD_CHNG_DAYS", "MAIN_ACCT_START", "MAIN_ACCT_LEN", "PFT_CTR_START", "PFT_CTR_LEN", "AR_CASH_DETL_DIST", "AR_CASH_DIST_REF", "AR_ADJ_DETL_DIST", "AR_ADJ_DIST_REF", "PS_SLS_DETL_DIST", "PS_SLS_DIST_REF", "PS_PMT_DETL_DIST", "PS_PMT_DIST_REF", "PS_MISC_DETL_DIST", "PS_MISC_DIST_REF", "PS_TAX_DETL_DIST", "PS_TAX_DIST_REF", "IM_RECV_DETL_DIST", "IM_RECV_DIST_REF", "IM_SLS_DETL_DIST", "IM_SLS_DIST_REF", "IM_ADJ_DETL_DIST", "IM_ADJ_DIST_REF", "IM_CNT_DETL_DIST", "IM_CNT_DIST_REF", "IM_XFER_DETL_DIST", "IM_XFER_DIST_REF", "PS_GFC_DETL_DIST", "PS_GFC_DIST_REF", "USE_GFC", "GFC_VAL_MONS", "NO_GFC_EXP", "ROUND_GFC_EXP_TO_EOM", "ALLOW_OTHR_STR_GFCS", "CLSD_GFC_JRNL_METH", "MIN_GFC_RDM_PCT", "PS_STC_DETL_DIST", "PS_STC_DIST_REF", "USE_STC", "STC_VAL_MONS", "NO_STC_EXP", "ROUND_STC_EXP_TO_EOM", "ALLOW_OTHR_STR_STCS", "CLSD_STC_JRNL_METH", "STC_LIAB_ACCT_NO", "STC_LIAB_METH", "STC_RDM_ACCT_NO", "STC_RDM_METH", "STC_FORF_ACCT_NO", "STC_FORF_METH", "MAX_LKUP_ROWS", "USE_FAST_OPN", "CLSD_GFC_JRNL_DIST", "CLSD_STC_JRNL_DIST", "LST_MAINT_DT", "LST_MAINT_USR_ID", "LST_LCK_DT", "IM_RTV_DETL_DIST", "IM_RTV_DIST_REF", "PS_PAY_IN_OUT_DETL_DIST", "PS_PAY_IN_OUT_DIST_REF", "PS_PAY_ON_ACCT_DETL_DIST", "PS_PAY_ON_ACCT_DIST_REF", "MAX_TBL_VIEW_ROWS", "PO_ADJ_DETL_DIST", "PO_ADJ_DIST_REF", "REQ_COMPLEX_PWD", "PREV_UNIQUE_PWDS", "LOGIN_ATTEMPTS", "USE_TIMCRDS", "STALE_CLCK_IN_HRS", "ALLOW_RE_CLCK_IN", "RE_CLCK_IN_MINS", "ALLOW_ORPHAN_CLCK_OUT", "TIMCRD_DFLT_USR_ID", "AR_FCH_DETL_DIST", "AR_FCH_DIST_REF", "PS_SVC_DETL_DIST", "PS_SVC_DIST_REF", "USE_SVC", "SVC_PROCESSOR", "SVC_MIN_ACTIV_AMT", "SVC_MIN_RECHRG_AMT", "SVC_MAX_RFND_AMT", "SVC_MAX_CASH_BACK_AMT", "NO_SVC_MAX_CASH_BACK_AMT", "REQ_SVC_PIN", "USE_WINDOWS_AUTH", "WINDOWS_AUTH_PATH", "OE_SLS_DETL_DIST", "OE_SLS_DIST_REF", "OE_PMT_DETL_DIST", "OE_PMT_DIST_REF", "OE_MISC_DETL_DIST", "OE_MISC_DIST_REF", "OE_TAX_DETL_DIST", "OE_TAX_DIST_REF", "OE_GFC_DETL_DIST", "OE_GFC_DIST_REF", "OE_STC_DETL_DIST", "OE_STC_DIST_REF", "OE_SVC_DETL_DIST", "OE_SVC_DIST_REF", "COPY_USR_BAT", "PROMPT_FOR_USR_BAT", "COPY_USR_DRW", "PROMPT_FOR_USR_DRW", "COPY_USR_PREF", "PROMPT_FOR_USR_PREF", "RS_UTC_DT", "IM_BOM_ASSEM_DETL_DIST", "IM_BOM_ASSEM_DIST_REF", "USE_GFT_RGSTRY", "ALLOW_OTHR_STR_GFT_RGSTRY", "GFT_RGSTRY_VAL_MONS", "MAIL_REFRSH_SECS", "MAIL_AUTO_PURGE_DAYS", "RESTRICT_TO_REGISTERED_WORKSTATIONS", "USE_EXT_EDC", "RPT_EMAIL_BODY", "SYS_ADMIN_EMAIL_ADRS", "RS_STAT", "USE_DROPSHIP", "SECURE_PAYMENT_DATA_MODE" FROM "SY_COMP" WHERE "KEY_ID" = @KEY_ID
PARAMS: KEY_ID=1
2017-05-05T14:13:37.81041 DEBUG STP SmartThreadPool Thread #2 OrmLiteReadCommandExtensions SQL: SELECT "KEY_ID", "DB_VER", "DB_TYP", "FULLTXT_SRCH", "SHARED_DIR", "LST_MAINT_DT", "LST_MAINT_USR_ID", "LST_LCK_DT", "AUTO_UPR", "DB_KIND" FROM "DB_CTL" WHERE "KEY_ID" = @KEY_ID
PARAMS: KEY_ID=1
2017-05-05T14:13:38.11347 DEBUG 8 AppSelfHostBase 192.168.0.61:52000 Request : /app/views/dashboard.htm
2017-05-05T14:13:40.35837 DEBUG 7 AppSelfHostBase 192.168.0.61:52000 Request : /Roles/Users
2017-05-05T14:13:40.35887 DEBUG 8 AppSelfHostBase 192.168.0.61:52000 Request : /Role/Endpoints
2017-05-05T14:13:40.46290 DEBUG STP SmartThreadPool Thread #3 OrmLiteReadCommandExtensions SQL: SELECT "Id", "Key", "Type", "Value" 
FROM "KeyValueData"
WHERE ((upper("Key") = @0) AND ("Type" = @1))
PARAMS: @0=ADMINS, @1=CPAPI.Common.CompanyAdmin
2017-05-05T14:13:40.46290 DEBUG STP SmartThreadPool Thread #4 OrmLiteReadCommandExtensions SQL: SELECT "Id", "Key", "Type", "Value" 
FROM "KeyValueData"
WHERE ((upper("Key") = @0) AND ("Type" = @1))
PARAMS: @0=ADMINS, @1=CPAPI.Common.CompanyAdmin
2017-05-05T14:13:40.49990 DEBUG STP SmartThreadPool Thread #4 RoleEndpointService GET request received
2017-05-05T14:13:40.50891 DEBUG STP SmartThreadPool Thread #3 RolesService GET request received
2017-05-05T14:13:40.51290 DEBUG STP SmartThreadPool Thread #3 OrmLiteReadCommandExtensions SQL: SELECT "Id", "Key", "Type", "Value" 
FROM "KeyValueData"
WHERE ("Type" = @0)
PARAMS: @0=CPAPI.Common.Role
2017-05-05T14:13:40.55191 DEBUG STP SmartThreadPool Thread #3 OrmLiteReadCommandExtensions SQL: SELECT "Id", "Key", "Type", "Value" 
FROM "KeyValueData"
WHERE ((upper("Key") = @0) AND ("Type" = @1))
PARAMS: @0=TEST, @1=CPAPI.Common.Role
2017-05-05T14:13:40.56892 DEBUG STP SmartThreadPool Thread #3 OrmLiteReadCommandExtensions SQL: SELECT "Id", "Key", "Type", "Value" 
FROM "KeyValueData"
WHERE ("Type" = @0)
PARAMS: @0=CPAPI.Common.UserRoles
2017-05-05T14:14:16.19956 DEBUG 8 AppSelfHostBase 192.168.0.61:52000 Request : /Customers
2017-05-05T14:14:16.21256 DEBUG STP SmartThreadPool Thread #5 OrmLiteReadCommandExtensions SQL: SELECT "Id", "Key", "Type", "Value" 
FROM "KeyValueData"
WHERE ((upper("Key") = @0) AND ("Type" = @1))
PARAMS: @0=MGR, @1=CPAPI.Common.UserRoles
2017-05-05T14:14:16.23057 DEBUG STP SmartThreadPool Thread #5 OrmLiteReadCommandExtensions SQL: SELECT "Id", "Key", "Type", "Value" 
FROM "KeyValueData"
WHERE ((upper("Key") = @0) AND ("Type" = @1))
PARAMS: @0=CORCRM, @1=CPAPI.Common.Database
2017-05-05T14:14:16.23556 ERROR STP SmartThreadPool Thread #5 ServiceStackHost Error occured while Processing Request: Invalid Registration
System.Exception: Invalid Registration
   at CPAPI.Common.RegistrationIniBusiness.ValidateRegistrationFile(String dbName)
   at CPAPI.Common.RegIniAttribute.Execute(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.RequestFilterAttribute.RequestFilter(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.Host.RestHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)

Please provide your guidance on this what I am missing.
Thanks & Regards
Amit

**Comment by MikeRitchie** [comment]
It appears your Counterpoint system (not API server) has an expired registration.ini, or your registration.ini does not contain the Counterpoint API option.

**Comment by amitcorcrm** [comment]
Thanks for reply.  Can you please let me know how do I check weather the Counterpoint API option is there or not. Also, if it was not there how can I add that in the registration.ini. Please let me know the way to resolve this issue.

**Comment by MikeRitchie** [comment]
I can see above that your registration.ini doesn't have the API option.  Please work with the Counterpoint partner that got you the registration.ini above to request a new file with the API option. Instructions for the Counterpoint partner to request the API option can be found on this page: https://github.com/NCRCounterpointAPI/APIGuide/blob/master/InstallationAndConfiguration/Licensing.md

**Comment by amitcorcrm** [comment]
Yes you right, issue is for registration.ini. I have updated  the registration.ini file and now i am able to fetch company  data using company end point API.
Thanks for you supports! 👍
