### ISSUE TITLE
UserRoles: Object value is null - GET Items

### ISSUE THREAD

**Issue by pheslop** [NCRCounterpointAPI/APIGuide#77]
Hi Mike,

We are testing on 8.5.3 and getting the following error when attempting a GET items
![image](https://user-images.githubusercontent.com/13469592/32555722-894a775a-c46b-11e7-990c-2b9d846748b3.png)

2017-11-08T02:14:37.77913 DEBUG 53 AppSelfHostBase 10.2.12.2:52000 Request : /Items
2017-11-08T02:14:37.78013 ERROR STP SmartThreadPool Thread #198 ServiceStackHost Error occured while Processing Request: An error occurred while trying to access an object of type: UserRoles, Object value is null,    at CPAPI.Common.RepositoryCompanyBase.GetCacheKeyName(Object[] cacheKeyId)
System.NullReferenceException: An error occurred while trying to access an object of type: UserRoles, Object value is null,    at CPAPI.Common.RepositoryCompanyBase.GetCacheKeyName(Object[] cacheKeyId)
   at CPAPI.Common.RepositoryCompanyBase.GetCacheKeyName(Object[] cacheKeyId)
   at CPAPI.Common.KeyValueDataRepository.GetValueByName[T](String key)
   at CPAPI.Common.UserRoleBusiness.CheckPermissions(String userId, String path, String verb)
   at CPAPI.Common.RoleAttribute.Execute(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.RequestFilterAttribute.RequestFilter(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)

**Comment by pheslop** [comment]
Also, the KeyValueData table is empty.  Looking at previous issues - this needs to have role data in it?

**Comment by MikeRitchie** [comment]
I would expect role data to be in the table, yes. Do you have a role created with permissions for GET /Items for that company and assigned to the user making the API call?

**Comment by pheslop** [comment]
Thanks, Mike.  I just created a role, figured that out.  But now I am getting a "unable to retrieve endpoint data: undefined" error
![image](https://user-images.githubusercontent.com/13469592/32557354-e4b6a290-c46f-11e7-949f-a2e30377854e.png)

**Comment by MikeRitchie** [comment]
What browser are you trying? If not Chrome, can you try with Chrome? Is the role successfully added and associated with the Counterpoint user you're using to authenticate the call?

**Comment by pheslop** [comment]
Hi Mike,

This was operator error.  User didn't realize you could click on the company name to see more options
