### ISSUE TITLE
Can't login as company admin

### ISSUE THREAD

**Issue by WingedDante** [NCRCounterpointAPI/APIGuide#9]
I went through all the installation steps, and have got to the point where you're supposed to add roles, after adding company admins, by logging in as a company admin with the <CompanyName/Alias>.<Username> format using Counterpoint credentials, and for the life of my I can't get logged in as my Counterpoint user.  I checked the log file and it wasn't very helpful: 
```
2017-03-14T10:15:02.71910 DEBUG 10 AppSelfHostBase 172.16.18.105:52000 Request : /auth
2017-03-14T10:15:02.72110 ERROR STP SmartThreadPool Thread #152 ServiceStackHost ServiceBase<TRequest>::Service Exception
ServiceStack.HttpError: Invalid UserName or Password
  at ServiceStack.Auth.CredentialsAuthProvider.Authenticate(IServiceBase authService, IAuthSession session, String userName, String password, String referrerUrl)
  at ServiceStack.Auth.BasicAuthProvider.Authenticate(IServiceBase authService, IAuthSession session, Authenticate request)
  at ServiceStack.Auth.AuthenticateService.Authenticate(Authenticate request, String provider, IAuthSession session, IAuthProvider oAuthConfig)
  at ServiceStack.Auth.AuthenticateService.Post(Authenticate request)
  at ServiceStack.Auth.BasicAuthProvider.PreAuthenticate(IRequest req, IResponse res)
  at ServiceStack.EnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 action)
  at ServiceStack.AuthenticateAttribute.Execute(IRequest req, IResponse res, Object requestDto)
  at ServiceStack.Auth.AuthenticateService.Post(Authenticate request)
  at ServiceStack.Host.ServiceRunner`1.Execute(IRequest request, Object instance, TRequest requestDto)
```
The information about the system that might be pertinent is we're using our windows credentials to log into counterpoint, and my User has no password in the counterpoint DB because it's just pointed to the domain to login.  I can't think of any other reason the correct username/password combo isn't working. Thoughts?

**Comment by MikeRitchie** [comment]
Hello,
Unfortunately, using windows credentials to login to Counterpoint isn't supported via the API yet. We'll look at what's involved in adding that. One thing that may be possible is to:
* Turn off windows authentication in Counterpoint
* Add a new Counterpoint user (for the API) with a password
* Turn windows authentication in Counterpoint back on
We think this will allow using the API user in Counterpoint via the API. We haven't had a chance to validate this yet though. Ultimately, the API validates the password hash stored in the Counterpoint database for the user, so if that information exists in the Counterpoint DB it should work.

**Comment by WingedDante** [comment]
Mike,

I followed those steps and made an API service account in Counterpoint to make the calls with a password, and it worked. Thanks for the help!
